# Exporter Configuration
exporter:
    name: "Prometheus Metrics Exporter"
    description: "General-purpose metrics collection and exposition"
    version: "3.0.0"
    metrics_port: 9101
    health_port: 9102
    poll_interval_sec: 5
    parallel_collection: true
    max_workers: 4
    failure_threshold: 20

# Logging Configuration
logging:
    level: "DEBUG"
    max_bytes: 10485760  # 10MB
    backup_count: 3

# Service Templates
service_templates:
    api_metrics:
        collection_frequency: 30
        content_type: "json"
        retry_attempts: 3
    
    file_monitor:
        collection_frequency: 300
        content_type: "json"
        watch_type: "config"

# Services Configuration
services:
    # Self-monitoring service
    exporter:
        name: "Metrics Exporter"
        description: "Self-monitoring metrics"
        metric_prefix: "exporter_"
        ordinal: 1
        expose_metrics: true
        
        metric_groups:
            status:
                prefix: "status_"
                ordinal: 1
                metrics:
                    uptime:
                        name: "uptime_seconds"
                        type: "gauge"
                        description: "Service uptime in seconds"
                        category: "health"
    
    # Algorand service configuration
    algorand:
        name: "Algorand Node"
        description: "Algorand node monitoring"
        metric_prefix: "algorand_"
        ordinal: 2
        expose_metrics: true
        
        run_as:
            user: algorand
            group: algorand
            env:
                ALGORAND_DATA: "/var/lib/algorand"
        
        metric_groups:
            node:
                prefix: "node_"
                template: "api_metrics"
                ordinal: 1
                metrics:
                    status:
                        name: "status"
                        type: "gauge"
                        description: "Node status information"
                        command: "sudo -u algorand /usr/bin/goal node status -d /var/lib/algorand"
                        filter: "Last committed block: (\\d+)"
                        category: "critical"
            
            storage:
                prefix: "storage_"
                ordinal: 2
                metrics:
                    data_size:
                        name: "data_size_bytes"
                        description: "Algorand data directory size"
                        command: "sudo -u algorand du -sb /var/lib/algorand"
                        filter: "^(\\d+)"
                        collection_frequency: 300
                        category: "performance"