# Prometheus Metrics Exporter Configuration
#
# Metric Types:
# - gauge    : A value that can go up and down (default)
# - static   : Fixed value specified in this configuration (specify "value" instead of a "command")
# - counter  : A value that only increases (not supported)
# - summary  : Basic statistics about values (not supported)
# - histogram: Distribution of values in buckets (not supported)

# Exporter Configuration
exporter:
    metrics_port: 9101
    health_port: 9102
    collection:
        poll_interval_sec: 5 # Global polling interval, override with collection_frequency (template, service, metric_group)
    logging:
        level: "DEBUG"

# Services Configuration
services:
    algorand_node:
        description: "Algorand node services"
        run_as: algorand
        metric_groups:
            status:
                command: "/usr/bin/goal node status -d /var/lib/algorand"
                metrics:
                    sync_time:
                        type: "gauge"
                        description: "Node synchronization time in seconds"
                        filter: "Sync Time: ([0-9.]+)s"
                        value_on_error: 999
            data_store:
                command: "du -sb /var/lib/algorand"
                metrics:
                    bytes:
                        type: "gauge"
                        description: "Algorand data storage directory size"
                        filter: "^(\\d+)"